classDiagram
    %%{init: {'flowchart': {'htmlLabels': true}}}%%
    class FusionSta...
    class FusionBoo...
    class Reflectio...
    class FusionRun...
    class Informaci...
    class AssetData...
    class NetworkSc...
    class UnitContr...
    class UnitView
    class FusionSta...
    class FusionSta...
    class RenderSim...
    class Controlad...
    class FusionEdi...
    class UnitModel
    class FusionEdi...
    class Enemigo
    class FusionPro...
    class FusionNet...
    class Bala
    class NetworkRu...
    class IA_P2_Age...
    class FusionGrid
    class NetworkOb...
    class Labels
    class IA_P2_FSM
    class Tanque
    class WeaponModel
    class NetworkCh...
    class RunnerEna...
    class RunnerVis...
    class Component...
    class IA_P2_FOV
    class FusionSta...
    class Character...
    class EnemyModel
    class GameManager
    class FusionBoo...
    class FusionSta...
    class LazyGUIStyle
    class FusionSta...
    class FixedBuff...
    class FusionCod...
    class RangeExAt...
    class FusionIns...
    class LogSettin...
    class FusionEdi...
    class DebugColi...
    class TickRateD...
    class Decoratin...
    class AnimatorC...
    class WeaponView
    class GenericDe...
    class Proyectil
    class EnumDrawer
    class PropertyD...
    class Transform...
    class FusionGlo...
    class Serialize...
    class SplitterS...
    class NetworkPr...
    class IA_P2_Pat...
    class PlayerCon...
    class UnitFSM
    class GEN_Inputs
    class LeaderMan...
    class NetworkAs...
    class JsonUtili...
    class NetworkOb...
    class FusionUni...
    class InternalT...
    class ScriptAtt...
    class NetworkPr...
    class NetworkPr...
    class EntrarAlT...
    class UnitComma...
    class RawDataDr...
    class EditorGUI
    class WeaponCon...
    class AssetEnum...

    PropertyD... <|-- FixedBuff...
    PropertyD... <|-- RangeExAt...
